version: "3"
services:
  poetica:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: poeticadb
    ports:
      - "5001:5001"
    restart: always
    depends_on:
      - postgres

  postgres:
    image: postgres:16.0-alpine
    container_name: poetica_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: poeticadb
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always

volumes:
  postgres:
